### ISSUE TITLE
Blank reviews found in ratings_test.txt

### ISSUE THREAD

**Issue by jiyang-kang** [e9t/nsmc#2]
Hi,
I found three empty reviews in `ratings_test.txt`: row **5746**, **7899**, **27097**.
What is the purpose of these blank data?

![Screen Shot 2020-06-02 at 16 46 05 PM](https://user-images.githubusercontent.com/16663823/83494228-eb98fe00-a4f0-11ea-9756-d0ce2c406166.png)

**Comment by e9t** [comment]
Hi, @jamiekang!
There was no particular intention and it would be better to remove such rows.
We should probably release a v1.1 of this corpus!

**Comment by jiyang-kang** [comment]
Hi, thanks for the notice.
it would be great if we can have an updated version of this dataset since it's now become a de facto standard in Korean sentiment analysis.
Maybe we can have bigger sets with multi-class labels (positive, negative, neutral, and mixed).

I will try to help.
